// Code generated by entc, DO NOT EDIT.

package userextend

import (
	"time"
)

const (
	// Label holds the string label denoting the userextend type in the database.
	Label = "user_extend"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatUserID holds the string denoting the plat_user_id field in the database.
	FieldPlatUserID = "plat_user_id"
	// FieldRealName holds the string denoting the real_name field in the database.
	FieldRealName = "real_name"
	// FieldIDNumber holds the string denoting the id_number field in the database.
	FieldIDNumber = "id_number"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldSex holds the string denoting the sex field in the database.
	FieldSex = "sex"
	// FieldBirth holds the string denoting the birth field in the database.
	FieldBirth = "birth"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldNickName holds the string denoting the nick_name field in the database.
	FieldNickName = "nick_name"
	// FieldImei holds the string denoting the imei field in the database.
	FieldImei = "imei"
	// FieldOaid holds the string denoting the oaid field in the database.
	FieldOaid = "oaid"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldSystemName holds the string denoting the system_name field in the database.
	FieldSystemName = "system_name"
	// FieldSystemVersion holds the string denoting the system_version field in the database.
	FieldSystemVersion = "system_version"
	// FieldAdid holds the string denoting the adid field in the database.
	FieldAdid = "adid"
	// FieldGameID holds the string denoting the game_id field in the database.
	FieldGameID = "game_id"
	// FieldThirdPlatformID holds the string denoting the third_platform_id field in the database.
	FieldThirdPlatformID = "third_platform_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the userextend in the database.
	Table = "plat_user_extend"
)

// Columns holds all SQL columns for userextend fields.
var Columns = []string{
	FieldID,
	FieldPlatUserID,
	FieldRealName,
	FieldIDNumber,
	FieldAge,
	FieldSex,
	FieldBirth,
	FieldIcon,
	FieldNickName,
	FieldImei,
	FieldOaid,
	FieldDeviceID,
	FieldSystemName,
	FieldSystemVersion,
	FieldAdid,
	FieldGameID,
	FieldThirdPlatformID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRealName holds the default value on creation for the "real_name" field.
	DefaultRealName string
	// DefaultIDNumber holds the default value on creation for the "id_number" field.
	DefaultIDNumber string
	// DefaultAge holds the default value on creation for the "age" field.
	DefaultAge int8
	// DefaultSex holds the default value on creation for the "sex" field.
	DefaultSex int8
	// DefaultBirth holds the default value on creation for the "birth" field.
	DefaultBirth int
	// DefaultIcon holds the default value on creation for the "icon" field.
	DefaultIcon string
	// DefaultNickName holds the default value on creation for the "nick_name" field.
	DefaultNickName string
	// DefaultImei holds the default value on creation for the "imei" field.
	DefaultImei string
	// DefaultOaid holds the default value on creation for the "oaid" field.
	DefaultOaid string
	// DefaultDeviceID holds the default value on creation for the "device_id" field.
	DefaultDeviceID string
	// DefaultSystemName holds the default value on creation for the "system_name" field.
	DefaultSystemName string
	// DefaultSystemVersion holds the default value on creation for the "system_version" field.
	DefaultSystemVersion string
	// DefaultAdid holds the default value on creation for the "adid" field.
	DefaultAdid string
	// DefaultGameID holds the default value on creation for the "game_id" field.
	DefaultGameID string
	// DefaultThirdPlatformID holds the default value on creation for the "third_platform_id" field.
	DefaultThirdPlatformID int8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
