// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"
	"user/internal/data/ent/schema"
	"user/internal/data/ent/user"
	"user/internal/data/ent/userextend"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserName is the schema descriptor for user_name field.
	userDescUserName := userFields[0].Descriptor()
	// user.DefaultUserName holds the default value on creation for the user_name field.
	user.DefaultUserName = userDescUserName.Default.(string)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescTelNum is the schema descriptor for tel_num field.
	userDescTelNum := userFields[2].Descriptor()
	// user.DefaultTelNum holds the default value on creation for the tel_num field.
	user.DefaultTelNum = userDescTelNum.Default.(string)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[3].Descriptor()
	// user.DefaultPassword holds the default value on creation for the password field.
	user.DefaultPassword = userDescPassword.Default.(string)
	// userDescPasswordStr is the schema descriptor for password_str field.
	userDescPasswordStr := userFields[4].Descriptor()
	// user.DefaultPasswordStr holds the default value on creation for the password_str field.
	user.DefaultPasswordStr = userDescPasswordStr.Default.(string)
	// userDescRegType is the schema descriptor for reg_type field.
	userDescRegType := userFields[5].Descriptor()
	// user.DefaultRegType holds the default value on creation for the reg_type field.
	user.DefaultRegType = userDescRegType.Default.(int8)
	// userDescRegisterIP is the schema descriptor for register_ip field.
	userDescRegisterIP := userFields[7].Descriptor()
	// user.DefaultRegisterIP holds the default value on creation for the register_ip field.
	user.DefaultRegisterIP = userDescRegisterIP.Default.(int)
	// userDescTelStatus is the schema descriptor for tel_status field.
	userDescTelStatus := userFields[8].Descriptor()
	// user.DefaultTelStatus holds the default value on creation for the tel_status field.
	user.DefaultTelStatus = userDescTelStatus.Default.(int8)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[9].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int8)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[10].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	userextendFields := schema.UserExtend{}.Fields()
	_ = userextendFields
	// userextendDescRealName is the schema descriptor for real_name field.
	userextendDescRealName := userextendFields[1].Descriptor()
	// userextend.DefaultRealName holds the default value on creation for the real_name field.
	userextend.DefaultRealName = userextendDescRealName.Default.(string)
	// userextendDescIDNumber is the schema descriptor for id_number field.
	userextendDescIDNumber := userextendFields[2].Descriptor()
	// userextend.DefaultIDNumber holds the default value on creation for the id_number field.
	userextend.DefaultIDNumber = userextendDescIDNumber.Default.(string)
	// userextendDescAge is the schema descriptor for age field.
	userextendDescAge := userextendFields[3].Descriptor()
	// userextend.DefaultAge holds the default value on creation for the age field.
	userextend.DefaultAge = userextendDescAge.Default.(int8)
	// userextendDescSex is the schema descriptor for sex field.
	userextendDescSex := userextendFields[4].Descriptor()
	// userextend.DefaultSex holds the default value on creation for the sex field.
	userextend.DefaultSex = userextendDescSex.Default.(int8)
	// userextendDescBirth is the schema descriptor for birth field.
	userextendDescBirth := userextendFields[5].Descriptor()
	// userextend.DefaultBirth holds the default value on creation for the birth field.
	userextend.DefaultBirth = userextendDescBirth.Default.(int)
	// userextendDescIcon is the schema descriptor for icon field.
	userextendDescIcon := userextendFields[6].Descriptor()
	// userextend.DefaultIcon holds the default value on creation for the icon field.
	userextend.DefaultIcon = userextendDescIcon.Default.(string)
	// userextendDescNickName is the schema descriptor for nick_name field.
	userextendDescNickName := userextendFields[7].Descriptor()
	// userextend.DefaultNickName holds the default value on creation for the nick_name field.
	userextend.DefaultNickName = userextendDescNickName.Default.(string)
	// userextendDescImei is the schema descriptor for imei field.
	userextendDescImei := userextendFields[8].Descriptor()
	// userextend.DefaultImei holds the default value on creation for the imei field.
	userextend.DefaultImei = userextendDescImei.Default.(string)
	// userextendDescOaid is the schema descriptor for oaid field.
	userextendDescOaid := userextendFields[9].Descriptor()
	// userextend.DefaultOaid holds the default value on creation for the oaid field.
	userextend.DefaultOaid = userextendDescOaid.Default.(string)
	// userextendDescDeviceID is the schema descriptor for device_id field.
	userextendDescDeviceID := userextendFields[10].Descriptor()
	// userextend.DefaultDeviceID holds the default value on creation for the device_id field.
	userextend.DefaultDeviceID = userextendDescDeviceID.Default.(string)
	// userextendDescSystemName is the schema descriptor for system_name field.
	userextendDescSystemName := userextendFields[11].Descriptor()
	// userextend.DefaultSystemName holds the default value on creation for the system_name field.
	userextend.DefaultSystemName = userextendDescSystemName.Default.(string)
	// userextendDescSystemVersion is the schema descriptor for system_version field.
	userextendDescSystemVersion := userextendFields[12].Descriptor()
	// userextend.DefaultSystemVersion holds the default value on creation for the system_version field.
	userextend.DefaultSystemVersion = userextendDescSystemVersion.Default.(string)
	// userextendDescAdid is the schema descriptor for adid field.
	userextendDescAdid := userextendFields[13].Descriptor()
	// userextend.DefaultAdid holds the default value on creation for the adid field.
	userextend.DefaultAdid = userextendDescAdid.Default.(string)
	// userextendDescGameID is the schema descriptor for game_id field.
	userextendDescGameID := userextendFields[14].Descriptor()
	// userextend.DefaultGameID holds the default value on creation for the game_id field.
	userextend.DefaultGameID = userextendDescGameID.Default.(string)
	// userextendDescThirdPlatformID is the schema descriptor for third_platform_id field.
	userextendDescThirdPlatformID := userextendFields[15].Descriptor()
	// userextend.DefaultThirdPlatformID holds the default value on creation for the third_platform_id field.
	userextend.DefaultThirdPlatformID = userextendDescThirdPlatformID.Default.(int8)
	// userextendDescCreatedAt is the schema descriptor for created_at field.
	userextendDescCreatedAt := userextendFields[16].Descriptor()
	// userextend.DefaultCreatedAt holds the default value on creation for the created_at field.
	userextend.DefaultCreatedAt = userextendDescCreatedAt.Default.(func() time.Time)
}
