// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"user/internal/data/ent/predicate"
	"user/internal/data/ent/userextend"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserExtendDelete is the builder for deleting a UserExtend entity.
type UserExtendDelete struct {
	config
	hooks    []Hook
	mutation *UserExtendMutation
}

// Where adds a new predicate to the UserExtendDelete builder.
func (ued *UserExtendDelete) Where(ps ...predicate.UserExtend) *UserExtendDelete {
	ued.mutation.predicates = append(ued.mutation.predicates, ps...)
	return ued
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ued *UserExtendDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ued.hooks) == 0 {
		affected, err = ued.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserExtendMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ued.mutation = mutation
			affected, err = ued.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ued.hooks) - 1; i >= 0; i-- {
			mut = ued.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ued.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ued *UserExtendDelete) ExecX(ctx context.Context) int {
	n, err := ued.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ued *UserExtendDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: userextend.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userextend.FieldID,
			},
		},
	}
	if ps := ued.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ued.driver, _spec)
}

// UserExtendDeleteOne is the builder for deleting a single UserExtend entity.
type UserExtendDeleteOne struct {
	ued *UserExtendDelete
}

// Exec executes the deletion query.
func (uedo *UserExtendDeleteOne) Exec(ctx context.Context) error {
	n, err := uedo.ued.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userextend.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uedo *UserExtendDeleteOne) ExecX(ctx context.Context) {
	uedo.ued.ExecX(ctx)
}
