// Code generated by entc, DO NOT EDIT.

package user

import (
	"time"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldTelNum holds the string denoting the tel_num field in the database.
	FieldTelNum = "tel_num"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldPasswordStr holds the string denoting the password_str field in the database.
	FieldPasswordStr = "password_str"
	// FieldRegType holds the string denoting the reg_type field in the database.
	FieldRegType = "reg_type"
	// FieldRegisterTime holds the string denoting the register_time field in the database.
	FieldRegisterTime = "register_time"
	// FieldRegisterIP holds the string denoting the register_ip field in the database.
	FieldRegisterIP = "register_ip"
	// FieldTelStatus holds the string denoting the tel_status field in the database.
	FieldTelStatus = "tel_status"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the user in the database.
	Table = "plat_user"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUserName,
	FieldEmail,
	FieldTelNum,
	FieldPassword,
	FieldPasswordStr,
	FieldRegType,
	FieldRegisterTime,
	FieldRegisterIP,
	FieldTelStatus,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUserName holds the default value on creation for the "user_name" field.
	DefaultUserName string
	// DefaultEmail holds the default value on creation for the "email" field.
	DefaultEmail string
	// DefaultTelNum holds the default value on creation for the "tel_num" field.
	DefaultTelNum string
	// DefaultPassword holds the default value on creation for the "password" field.
	DefaultPassword string
	// DefaultPasswordStr holds the default value on creation for the "password_str" field.
	DefaultPasswordStr string
	// DefaultRegType holds the default value on creation for the "reg_type" field.
	DefaultRegType int8
	// DefaultRegisterIP holds the default value on creation for the "register_ip" field.
	DefaultRegisterIP int
	// DefaultTelStatus holds the default value on creation for the "tel_status" field.
	DefaultTelStatus int8
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
