// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PlatUserColumns holds the columns for the "plat_user" table.
	PlatUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_name", Type: field.TypeString, Default: ""},
		{Name: "email", Type: field.TypeString, Default: ""},
		{Name: "tel_num", Type: field.TypeString, Default: ""},
		{Name: "password", Type: field.TypeString, Default: ""},
		{Name: "password_str", Type: field.TypeString, Default: ""},
		{Name: "reg_type", Type: field.TypeInt8, Default: 0},
		{Name: "register_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "register_ip", Type: field.TypeInt, Default: 0},
		{Name: "tel_status", Type: field.TypeInt8, Default: 2},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp"}},
	}
	// PlatUserTable holds the schema information for the "plat_user" table.
	PlatUserTable = &schema.Table{
		Name:        "plat_user",
		Columns:     PlatUserColumns,
		PrimaryKey:  []*schema.Column{PlatUserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PlatUserExtendColumns holds the columns for the "plat_user_extend" table.
	PlatUserExtendColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "plat_user_id", Type: field.TypeUint},
		{Name: "real_name", Type: field.TypeString, Default: ""},
		{Name: "id_number", Type: field.TypeString, Default: ""},
		{Name: "age", Type: field.TypeInt8, Default: 0},
		{Name: "sex", Type: field.TypeInt8, Default: 1},
		{Name: "birth", Type: field.TypeInt, Default: 0},
		{Name: "icon", Type: field.TypeString, Default: ""},
		{Name: "nick_name", Type: field.TypeString, Default: ""},
		{Name: "imei", Type: field.TypeString, Default: ""},
		{Name: "oaid", Type: field.TypeString, Default: ""},
		{Name: "device_id", Type: field.TypeString, Default: ""},
		{Name: "system_name", Type: field.TypeString, Default: ""},
		{Name: "system_version", Type: field.TypeString, Default: ""},
		{Name: "adid", Type: field.TypeString, Default: ""},
		{Name: "game_id", Type: field.TypeString, Default: ""},
		{Name: "third_platform_id", Type: field.TypeInt8, Default: 0},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "timestamp"}},
	}
	// PlatUserExtendTable holds the schema information for the "plat_user_extend" table.
	PlatUserExtendTable = &schema.Table{
		Name:        "plat_user_extend",
		Columns:     PlatUserExtendColumns,
		PrimaryKey:  []*schema.Column{PlatUserExtendColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PlatUserTable,
		PlatUserExtendTable,
	}
)

func init() {
	PlatUserTable.Annotation = &entsql.Annotation{
		Table: "plat_user",
	}
	PlatUserExtendTable.Annotation = &entsql.Annotation{
		Table: "plat_user_extend",
	}
}
